language: node_js
node_js:
  - "7"

install:
  - npm install
  - npm install -g mocha

services:
  - mongodb

script: nyc npm test && nyc report --reporter=text-lcov | ./node_modules/coveralls/bin/coveralls.js